void spyJump(){
asm("jmp spy2;");
asm("nop;");asm("nop;");asm("nop;");
asm("spy2:");
asm("jmp spy3;");
asm("nop;");asm("nop;");asm("nop;");
asm("spy3:");
asm("jmp spy4;");
asm("nop;");asm("nop;");asm("nop;");
asm("spy4:");
asm("jmp spy5;");
asm("nop;");asm("nop;");asm("nop;");
asm("spy5:");
asm("jmp spy6;");
asm("nop;");asm("nop;");asm("nop;");
asm("spy6:");
asm("jmp spy7;");
asm("nop;");asm("nop;");asm("nop;");
asm("spy7:");
asm("jmp spy8;");
asm("nop;");asm("nop;");asm("nop;");
asm("spy8:");
asm("jmp spy9;");
asm("nop;");asm("nop;");asm("nop;");
asm("spy9:");
asm("jmp spy10;");
asm("nop;");asm("nop;");asm("nop;");
asm("spy10:");
asm("jmp spy11;");
asm("nop;");asm("nop;");asm("nop;");
asm("spy11:");
asm("jmp spy12;");
asm("nop;");asm("nop;");asm("nop;");
asm("spy12:");
asm("jmp spy13;");
asm("nop;");asm("nop;");asm("nop;");
asm("spy13:");
asm("jmp spy14;");
asm("nop;");asm("nop;");asm("nop;");
asm("spy14:");
asm("jmp spy15;");
asm("nop;");asm("nop;");asm("nop;");
asm("spy15:");
asm("jmp spy16;");
asm("nop;");asm("nop;");asm("nop;");
asm("spy16:");
asm("jmp spy17;");
asm("nop;");asm("nop;");asm("nop;");
asm("spy17:");
}